package com.aohaitong.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.aohaitong.bean.FriendBean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table "FRIEND_BEAN".
 */
public class FriendBeanDao extends AbstractDao<FriendBean, String> {

    public static final String TABLENAME = "FRIEND_BEAN";

    /**
     * Properties of entity FriendBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property NowLoginTel = new Property(0, String.class, "nowLoginTel", false, "NOW_LOGIN_TEL");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property NickName = new Property(2, String.class, "nickName", false, "NICK_NAME");
        public final static Property Telephone = new Property(3, String.class, "telephone", true, "TELEPHONE");
    }


    public FriendBeanDao(DaoConfig config) {
        super(config);
    }

    public FriendBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FRIEND_BEAN\" (" + //
                "\"NOW_LOGIN_TEL\" TEXT," + // 0: nowLoginTel
                "\"NAME\" TEXT," + // 1: name
                "\"NICK_NAME\" TEXT," + // 2: nickName
                "\"TELEPHONE\" TEXT PRIMARY KEY NOT NULL );"); // 3: telephone
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FRIEND_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FriendBean entity) {
        stmt.clearBindings();
 
        String nowLoginTel = entity.getNowLoginTel();
        if (nowLoginTel != null) {
            stmt.bindString(1, nowLoginTel);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(3, nickName);
        }
 
        String telephone = entity.getTelephone();
        if (telephone != null) {
            stmt.bindString(4, telephone);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FriendBean entity) {
        stmt.clearBindings();
 
        String nowLoginTel = entity.getNowLoginTel();
        if (nowLoginTel != null) {
            stmt.bindString(1, nowLoginTel);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(3, nickName);
        }

        String telephone = entity.getTelephone();
        if (telephone != null) {
            stmt.bindString(4, telephone);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3);
    }

    @Override
    public FriendBean readEntity(Cursor cursor, int offset) {
        FriendBean entity = new FriendBean( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // nowLoginTel
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nickName
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // telephone
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, FriendBean entity, int offset) {
        entity.setNowLoginTel(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNickName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTelephone(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
    }

    @Override
    protected final String updateKeyAfterInsert(FriendBean entity, long rowId) {
        return entity.getTelephone();
    }

    @Override
    public String getKey(FriendBean entity) {
        if (entity != null) {
            return entity.getTelephone();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FriendBean entity) {
        return entity.getTelephone() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
